## Step 1: Import Libraries

In [1]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.4.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

In [3]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

In [4]:
import pandas as pd
import re
import nltk

nltk.download('stopwords')

from nltk.corpus import stopwords

from sklearn.model_selection import train_test_split

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import accuracy_score, classification_report

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [5]:
data = {
    "Article": [

        # Sports
        "India won the cricket match.",
        "The football team reached the finals.",
        "The tennis player won the championship.",
        "The athlete broke a world record.",

        # Politics
        "The government announced a new policy.",
        "The election results were declared today.",
        "The parliament passed a new bill.",
        "The minister addressed the public meeting.",

        # Technology
        "Artificial Intelligence is changing industries.",
        "The company launched a new smartphone.",
        "Cybersecurity is becoming more important.",
        "Cloud computing is widely used.",

        # Entertainment
        "The movie became a blockbuster hit.",
        "The actor won a national award.",
        "The music concert attracted thousands.",
        "The actress announced her new film.",

        # Business
        "The company reported higher profits.",
        "Stock markets closed higher today.",
        "The startup received funding from investors.",
        "The bank introduced new loan schemes."

    ],

    "Category":[

        "Sports","Sports","Sports","Sports",

        "Politics","Politics","Politics","Politics",

        "Technology","Technology","Technology","Technology",

        "Entertainment","Entertainment","Entertainment","Entertainment",

        "Business","Business","Business","Business"
    ]
}

df = pd.DataFrame(data)

df.head()

                                   Article  Category
0             India won the cricket match.    Sports
1    The football team reached the finals.    Sports
2  The tennis player won the championship.    Sports
3        The athlete broke a world record.    Sports
4   The government announced a new policy.  Politics

In [6]:
stop_words = set(stopwords.words("english"))

def clean_text(text):

    text = text.lower()

    text = re.sub(r'[^a-zA-Z ]','',text)

    words = text.split()

    words = [word for word in words if word not in stop_words]

    return " ".join(words)

df["Cleaned_Article"] = df["Article"].apply(clean_text)

df.head()

,Article,Category,Cleaned_Article
0,India won the cricket match.,Sports,india cricket match
1,The football team reached the finals.,Sports,football team reached finals
2,The tennis player won the championship.,Sports,tennis player championship
3,The athlete broke a world record.,Sports,athlete broke world record
4,The government announced a new policy.,Politics,government announced new policy

In [7]:
vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(df["Cleaned_Article"])

y = df["Category"]

In [8]:
X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,
    test_size=0.3,
    random_state=42
)

In [9]:
model = MultinomialNB()

model.fit(X_train, y_train)

MultinomialNB()

In [10]:
prediction = model.predict(X_test)

print(prediction)

['Technology' 'Business' 'Politics' 'Technology' 'Technology' 'Technology']

In [11]:
print("Accuracy:", accuracy_score(y_test, prediction))

print()

print(classification_report(y_test, prediction))

Accuracy: 0.3333333333333333

               precision    recall  f1-score   support

     Business       1.00      1.00      1.00         1
Entertainment       0.00      0.00      0.00         1
     Politics       0.00      0.00      0.00         1
       Sports       0.00      0.00      0.00         2
   Technology       0.25      1.00      0.40         1

     accuracy                           0.33         6
    macro avg       0.25      0.40      0.28         6
 weighted avg       0.21      0.33      0.23         6

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [12]:
new_articles = [

    "The cricket team won the tournament.",

    "The government introduced a new tax.",

    "The company launched an AI robot.",

    "The actor released a new movie.",

    "Stock prices increased today."

]

new_articles = [clean_text(i) for i in new_articles]

new_vector = vectorizer.transform(new_articles)

result = model.predict(new_vector)

for article, category in zip(new_articles, result):

    print(article," --> ",category)

cricket team tournament  -->  Technology
government introduced new tax  -->  Politics
company launched ai robot  -->  Technology
actor released new movie  -->  Entertainment
stock prices increased today  -->  Technology